<a href="https://colab.research.google.com/github/MehrabHussain47/Python-Self-Practice/blob/master/Class_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Attributes and Advanced Pandas Operations

# টপিক:

# Data Cleaning with Pandas
# Handling Missing Data
# Dropping and Filling Data
# Basic Data Aggregations in Pandas (sum(), mean(), median(), count())

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.DataFrame(
    {
        'Name': ['Alice', 'Bob', np.nan, 'Daisy', 'Ethan'],
        'Age' : [25, np.nan, 29, 22, np.nan], # np.nan is for null value
        'salary':[50000, 60000, np.nan, 50000, 62000]
    }
)

In [ ]:
data.head()

,Name,Age,salary
0,Alice,25.0,50000.0
1,Bob,NaN,60000.0
2,NaN,29.0,NaN
3,Daisy,22.0,50000.0
4,Ethan,NaN,62000.0


In [ ]:
data_dropna = data.dropna()

In [ ]:
data_dropna.head()

,Name,Age,salary
0,Alice,25.0,50000.0
3,Daisy,22.0,50000.0


In [ ]:
data_filled = data.fillna(
    {
        'Name': 'Unknown',
        'Age': data['Age'].mean(),
        'salary': 0
    }
)

In [ ]:
data_filled.head()

,Name,Age,salary
0,Alice,25.000000,50000.0
1,Bob,25.333333,60000.0
2,Unknown,29.000000,0.0
3,Daisy,22.000000,50000.0
4,Ethan,25.333333,62000.0


In [ ]:
data_filled['Age'] = data_filled['Age'].astype(int)

In [ ]:
data_filled.head()

,Name,Age,salary
0,Alice,25,50000.0
1,Bob,25,60000.0
2,Unknown,29,0.0
3,Daisy,22,50000.0
4,Ethan,25,62000.0


In [ ]:
data_filled['salary'] = data_filled['salary'].astype(int)

In [ ]:
data_filled.head()

,Name,Age,salary
0,Alice,25,50000
1,Bob,25,60000
2,Unknown,29,0
3,Daisy,22,50000
4,Ethan,25,62000


In [ ]:
# 1D Array
np_array = np.array([1, 2, 3])

In [ ]:
np_array

array([1, 2, 3])

In [ ]:
# 2D Array
np_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np_array  # Matrix size (2 X 3) => we can call 2 by 3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
reshape_array = np_array.reshape(3, 2)

In [ ]:
reshape_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Now we can convert in 1D array
reshape_array = np_array.reshape(-1)

In [ ]:
reshape_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshape_array = np_array.reshape(1, 6)

In [ ]:
reshape_array

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
reshape_array[0]  # we can show the index of reshape_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Join Array
# We can see the vertical join
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6]])

In [ ]:
# Vertical Stacked Join => Vertically Join
v_stacked = np.vstack([a, b])

In [ ]:
# Dimenstion same hote hobe => column number same hote hobe
v_stacked # a array er row borabor b array join hobe

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# We can see the horizontal join
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
# Horizontal Join => column borabor join hobe
# Horizontal Join e row number same hote hobe
h_stacked = np.hstack([a, b])

In [ ]:
h_stacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# We can see the depth wise join
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# Depth Wise Join => height wise join hishebe kaj kore
# Ekhetre a and b er shape same hote hobe
d_stacked = np.dstack([a, b]) # 2D array to 3D array create hobe

In [ ]:
# we can see that 1st row of a and 1st row of b mile ekta 2D matrix
# 2nd row of a and 2nd row of b mile 2D matrix.
d_stacked

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [ ]:
np_array = np.array([[[1, 2, 3, 6], [3, 4, 5, 6]], [[5, 6, 7, 8], [7, 8, 9, 0]]])

In [ ]:
np_array   # This is a 3D matrix

array([[[1, 2, 3, 6],
        [3, 4, 5, 6]],

       [[5, 6, 7, 8],
        [7, 8, 9, 0]]])

In [ ]:
# Spliting Array
big_array = np.arange(10)

In [ ]:
big_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
split_array = np.split(big_array, 2) # Danpashe koyta vaghe vag korbo sheta
# 3 vage vag kora jabe na karon splitting ta similar dimention e hote hobe

In [ ]:
split_array

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
split_array[0] # Prothom array ta pabo

array([0, 1, 2, 3, 4])

In [ ]:
split_array[1] # Porer array ta pabo

array([5, 6, 7, 8, 9])

In [ ]:
# Searching Array
sorted_array = np.array([10, 20, 30, 40])

In [ ]:
# 25 ta boshate chai 25 ta kothay boshabo
pos = np.searchsorted(sorted_array, 25)

In [ ]:
pos # 2 number position dekhabe

np.int64(2)

In [ ]:
# 15 ta boshate chai 15 ta kothay boshabo
pos = np.searchsorted(sorted_array, 15)

In [ ]:
pos

np.int64(1)

In [117]:
# Where diye finding kora jabe
# Ekhane unsorted array er modhe kora jabe
sorted_array = np.array([101, 200, 30, 44])

In [118]:
value_find = np.where(sorted_array == 30)

In [119]:
value_find  # position bole dibe

(array([2]),)

In [120]:
even = np.where(sorted_array % 2 == 0)  # even value gulo khujte chacchi

In [121]:
even # even value position bole dibe

(array([1, 2, 3]),)

In [125]:
data.head()

,Name,Age,salary
0,Alice,25.0,50000.0
1,Bob,NaN,60000.0
2,NaN,29.0,NaN
3,Daisy,22.0,50000.0
4,Ethan,NaN,62000.0


In [126]:
# Dataframe e sort kora jay
# Ascending sort korte parbo
sorted_data = data.sort_values(by='salary', ascending=False)

In [127]:
sorted_data.head()

,Name,Age,salary
4,Ethan,NaN,62000.0
1,Bob,NaN,60000.0
0,Alice,25.0,50000.0
3,Daisy,22.0,50000.0
2,NaN,29.0,NaN


In [128]:
# Descending sort korte parbo
sorted_data = data.sort_values(by='salary', ascending=True)

In [129]:
sorted_data.head()

,Name,Age,salary
0,Alice,25.0,50000.0
3,Daisy,22.0,50000.0
1,Bob,NaN,60000.0
4,Ethan,NaN,62000.0
2,NaN,29.0,NaN


In [130]:
# Sorting Array
arr = np.array([6, 3, 8, 0])

In [131]:
arr

array([6, 3, 8, 0])

In [132]:
print(np.sort(arr))

[0 3 6 8]


In [133]:
arr = np.array([True, True, False, True])

In [134]:
arr

array([ True,  True, False,  True])

In [135]:
print(np.sort(arr))

[False  True  True  True]


In [138]:
arr = np.array(["banana", "Cherry", "Apple", "mango"])

In [139]:
arr

array(['banana', 'Cherry', 'Apple', 'mango'], dtype='<U6')

In [140]:
print(np.sort(arr))

['Apple' 'Cherry' 'banana' 'mango']


In [141]:
# Descending Sort
arr = np.array([6, 3, 8, 0])

In [142]:
arr

array([6, 3, 8, 0])

In [143]:
print(np.sort(arr)[::-1])

[8 6 3 0]


In [145]:
arr = np.array([True, True, False, True])

In [146]:
arr

array([ True,  True, False,  True])

In [147]:
print(np.sort(arr)[::-1])

[ True  True  True False]


In [148]:
arr = np.array(["Banana", "Cherry", "Apple", "mango"])

In [149]:
arr

array(['Banana', 'Cherry', 'Apple', 'mango'], dtype='<U6')

In [150]:
print(np.sort(arr)[::-1])

['mango' 'Cherry' 'Banana' 'Apple']


In [152]:
# Example
print(np.sort(arr)[3:1:-1])

['mango' 'Cherry']
