<a href="https://colab.research.google.com/github/MehrabHussain47/Python-Self-Practice/blob/master/Class_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [ ]:
# List
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [ ]:
# NumPy Array
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)

[5 7 9]


In [ ]:
# Initializing NumPy Arrays
menu = np.array(['cheese', 'bbq', 'veg', 'spicy'])  # menu of pizzashop
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [ ]:
# Key difference between list and numpy array
prices = [100, 200, 150, 220] # prices of pizzashop
prices = prices * 0.8
print(prices)

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
prices_np = np.array([100.8, 200, 150, 220])
discounted_price = prices_np * 0.8  # I want to give a discount for pizza
discounted_price

array([ 80.64, 160.  , 120.  , 176.  ])

In [ ]:
# Zeros
# 0 = no order table is empty
# 1 = table is booked there is an order
empty_table = np.zeros((3,3)) # 3 into 3 matrix
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Ones
booked_table = np.ones((3,3))
print(booked_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Full
bbq_boxes = np.full((2,3), 'bbq') # in Friday all the sold pizzas are bbq
print("BBQ boxes:\n",bbq_boxes)

BBQ boxes:
 [['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [ ]:
# Rand
surprise_toppings = np.random.rand(2,3) # there will be free toppings (percentage)
print(surprise_toppings) # by default the value will be in between 0 to 1

[[0.96613777 0.72654429 0.98531169]
 [0.15815567 0.52257719 0.89143202]]


In [ ]:
# Randint
# there will be lottery system for kids how many slice they will get
kids_order = np.random.randint(1,8, size = (2,3))
print(kids_order)


[[7 1 6]
 [5 2 2]]


In [ ]:
# Identity
# I will give free pizzas for signature table (identity)
signature_pizzas = np.identity(4)
print(signature_pizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Arange Functions
# Create delivery time for deliver pizza
delivery_times = np.arange(0, 120, 15) # in minutes 0 to 120
delivery_times_2 = np.arange(0, 70, 15)
print(delivery_times)
print(delivery_times_2)

[  0  15  30  45  60  75  90 105]
[ 0 15 30 45 60]


In [ ]:
# Linspace Functions
# Allocating time for chef to cook pizza
cooking_shifts = np.linspace(0, 120, 5)
cooking_shifts_2 = np.linspace(0, 70, 5)
print(cooking_shifts)
print(cooking_shifts_2)

[  0.  30.  60.  90. 120.]
[ 0.  17.5 35.  52.5 70. ]


In [ ]:
#Indexing & Slicing (1D Arrays)
# Pizza's order -> cheese, veg, spicy, bbq
# Now I forgot my order list and I have to find any pizza
orders = np.array(['cheese', 'veg', 'spicy', 'bbq'])
print(orders[2])
print(orders[1:3])
print(len(orders))
print(orders[:2])

spicy
['veg' 'spicy']
4
['cheese' 'veg']


In [ ]:
#Indexing & Slicing (2D Arrays)
orders = np.array([
    ['cheese', 'veg'],
    ['spicy', 'bbq']
])
print(orders[0,1])

veg


In [ ]:
print(orders[1,0])

spicy


In [ ]:
print(orders[:,0]) # print first column

['cheese' 'spicy']


In [ ]:
print(orders[:1, 0]) # 0 number row to not in 1 number row

['cheese']


In [ ]:
print(orders[1,0:]) # 1 number column to not in 0 number column

['spicy' 'bbq']


In [ ]:
print(orders[0,1:]) # 0 will be row and 1 will be column

['veg']


In [ ]:
print(orders[1,1:]) # 1 will be row and 1 will be column

['bbq']


In [ ]:
print(orders[:1,0]) # 0 will be row and 1 will be column

['cheese']


In [ ]:
print(orders[:1]) # it will print 1 row

[['cheese' 'veg']]


In [ ]:
print(orders[:2]) # It will print 2 rows

[['cheese' 'veg']
 ['spicy' 'bbq']]


In [ ]:
print(orders[:1,1] ) # 1 row and 1st index

['veg']


In [ ]:
print(orders[:2,1]) # 2 rows and 1st index

['veg' 'bbq']


In [ ]:
print(orders[:2,0]) # 2 rows and 0th index

['cheese' 'spicy']


In [49]:
# max(), min(), argmax(), argmin(), sum() fuctions
# Total sales of pizzashop
sales = np.array([120, 150, 90, 200])
print("Max sales:", np.max(sales))  # Max value of sales pizza
print("Max seller index:", np.argmax(sales))  # Index of max value of sales pizza
print("Min sales:", np.min(sales))  # Min value of sales pizza
print("Min seller index:", np.argmin(sales))  # Index of min value of sales pizza
print("Total sales:", np.sum(sales))  # Total sales of pizzashop

Max sales: 200
Max seller index: 3
Min sales: 90
Min seller index: 2
Total sales: 560
