<a href="https://colab.research.google.com/github/MehrabHussain47/Python-Self-Practice/blob/master/Class_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this kernel we will learn about using numpy and pandas libraries for data manipulation from scratch, instead of going into theory, we'll take a practical approach.

First we'll understand the syntax and commonly used functions of the numpy and pandas libraries. Later we'll work on a real-life data set.

NumPy (or Numpy) is a Linear Algebra Library for Python. the reason it is so important for Data Science with Python is that almost all the libraries in the PyData Ecosystem rely on Numpy as one of their main building blocks.

Numpy is incredibly fast, as it has binding to C libraries. We will only learn the basics of Numpy, to get started we need to install it!

Installation Instructions It is highly recommended you install Python using the Anaconda distribution to make sure all undefying dependencies (such as Linear Algebra libraries) all sync up with date with the use of a conda install, If you have Anaconda, install Numpy by going to your terminal or command prompt and typing:

!pip install numpy if you do not have Anaconda and can not install it, please refer to Numpy's official documentation from various installation instructions.

Numpy has many built-in function and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy:
vectors, arrays, matrices and number generation. Let's start by discussing arrays:

Numpy Arrays Numpy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d array and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create Numpy arrays:

In [13]:
!pip install numpy

# Starting with Numpy

In [14]:
# Load the library and check it's version, just to make sure we aren't using an older version
import numpy as np
np.__version__

'2.0.2'

In [4]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.6.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.6
ale-py                                0.11.0
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.0.2
astropy-iers-data                     0.2025.5.12.0.38.29
astunparse                            1

In [10]:
# Create a list comprising numbers from 0 to 20
L = list(range(21))
print(L)
# Create another list comprising numbers from 0 to 40
L2 = list(range(41))
print(L2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [5]:
# Converting integer to string - this type of handling lists is known as list comprehension.
[str(c) for c in L]

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20']

In [11]:
# List comprehenstion offers a versatile way to handle list manipulations tasks easily.
[type(item) for item in L]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int]

# Creating Arrays

Numpy arrays are homogeneous in nature i.e. they comprise one data type(integer, float, double etc.) unlike lists.

In [15]:
# Creating arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
my_list = [1, 2, 3]
print(my_list)

[1, 2, 3]


In [21]:
np.array(my_list)

array([1, 2, 3])

In [22]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [23]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Bulit-in-Methods. There are lots of built-in ways to generate Arrays.

arange Return evenly spaced values within a given interval.

In [31]:
np.arange(0,11)
# np.arange(20,31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# np.arange(0,11,2)
# np.arange(0,21,3)
np.arange(0,21,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

zeros and ones Generate arrays of zeros or ones.

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Creating a 3 row x 8 column matrix
np.ones((3,8), dtype='float')

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.ones((3,8), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [42]:
# Creating a matrix with a predefined value
np.full((3,5), 1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [43]:
# Create an array with a set sequence.
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
# Create an array of even space between the given range of values.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# Create a 3x3 array with mean 0 and standard deviation 1 in a given dimension.
np.random.normal(0, 1, (3,3))

array([[ 0.28739065, -0.83914531,  1.23654401],
       [ 0.33672973,  0.92023398,  1.61511074],
       [ 0.53155815,  0.68275915,  1.24746222]])

In [46]:
# Create an identity matrix.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
# Set a random seed.
np.random.seed(0)

x1 = np.random.randint(10, size=4)  # one dimension
x2 = np.random.randint(10, size=(3,5))  # two dimension
x3 = np.random.randint(10, size=(3,4,5))  # three dimenstion

print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size:", x1.size)

x1 ndim: 1
x1 shape: (4,)
x1 size: 4


In [50]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)

x2 ndim: 2
x2 shape: (3, 5)
x2 size: 15


In [51]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


# Array Indexing

The important thing to remember is that indexing in python starts at zero.

In [52]:
x1 = np.array([4,3,4,4,8,4])
x1

array([4, 3, 4, 4, 8, 4])

In [53]:
# access value to index zero.
x1[0]

np.int64(4)

In [54]:
# access fifth value
x1[4]

np.int64(8)

In [55]:
# get the last value
x1[-1]

np.int64(4)

In [56]:
# get the second last value
x1[-2]

np.int64(8)

In [58]:
# in a multidimensional array, we need to specify row and column index
x2 = np.array([[3,7,5,5],[0,1,5,9],[3,0,5,0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [60]:
# 3rd row and the last column value (4th column) from the 3rd row
x2[2,-1]

np.int64(0)

In [61]:
# replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

# Array Slicing

Now, we will learn to access multiple or a range of elements from an array.

In [62]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
# from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [64]:
# from 4th position to end
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
# from 4th to 6th position
x[4:7]

array([4, 5, 6])